// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: readinglist.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadingListEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId      string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NovelId        string                 `protobuf:"bytes,3,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter float64                `protobuf:"fixed64,5,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Rating         int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Notes          string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,8,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	CreatedAt      []byte                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      []byte                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadingListEntry) Reset() {
	*x = ReadingListEntry{}
	mi := &file_readinglist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingListEntry) ProtoMessage() {}

func (x *ReadingListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingListEntry.ProtoReflect.Descriptor instead.
func (*ReadingListEntry) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{0}
}

func (x *ReadingListEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadingListEntry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ReadingListEntry) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *ReadingListEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReadingListEntry) GetCurrentChapter() float64 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *ReadingListEntry) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReadingListEntry) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ReadingListEntry) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *ReadingListEntry) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReadingListEntry) GetUpdatedAt() []byte {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddToReadingListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	NovelId        string                 `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter float64                `protobuf:"fixed64,4,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Rating         int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	Notes          string                 `protobuf:"bytes,6,opt,name=notes,proto3" json:"notes,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,7,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddToReadingListRequest) Reset() {
	*x = AddToReadingListRequest{}
	mi := &file_readinglist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToReadingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToReadingListRequest) ProtoMessage() {}

func (x *AddToReadingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToReadingListRequest.ProtoReflect.Descriptor instead.
func (*AddToReadingListRequest) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{1}
}

func (x *AddToReadingListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AddToReadingListRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *AddToReadingListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AddToReadingListRequest) GetCurrentChapter() float64 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *AddToReadingListRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *AddToReadingListRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *AddToReadingListRequest) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type ReadingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *ReadingListEntry      `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadingListResponse) Reset() {
	*x = ReadingListResponse{}
	mi := &file_readinglist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadingListResponse) ProtoMessage() {}

func (x *ReadingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadingListResponse.ProtoReflect.Descriptor instead.
func (*ReadingListResponse) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{2}
}

func (x *ReadingListResponse) GetEntry() *ReadingListEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type UpdateReadingListRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CurrentChapter float64                `protobuf:"fixed64,3,opt,name=current_chapter,json=currentChapter,proto3" json:"current_chapter,omitempty"`
	Rating         int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Notes          string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	IsFavorite     bool                   `protobuf:"varint,6,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateReadingListRequest) Reset() {
	*x = UpdateReadingListRequest{}
	mi := &file_readinglist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadingListRequest) ProtoMessage() {}

func (x *UpdateReadingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadingListRequest.ProtoReflect.Descriptor instead.
func (*UpdateReadingListRequest) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateReadingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateReadingListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateReadingListRequest) GetCurrentChapter() float64 {
	if x != nil {
		return x.CurrentChapter
	}
	return 0
}

func (x *UpdateReadingListRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateReadingListRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateReadingListRequest) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

type GetReadingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Skip          uint64                 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingListRequest) Reset() {
	*x = GetReadingListRequest{}
	mi := &file_readinglist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingListRequest) ProtoMessage() {}

func (x *GetReadingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingListRequest.ProtoReflect.Descriptor instead.
func (*GetReadingListRequest) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{4}
}

func (x *GetReadingListRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetReadingListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetReadingListRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *GetReadingListRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type GetReadingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ReadingListEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReadingListResponse) Reset() {
	*x = GetReadingListResponse{}
	mi := &file_readinglist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReadingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReadingListResponse) ProtoMessage() {}

func (x *GetReadingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReadingListResponse.ProtoReflect.Descriptor instead.
func (*GetReadingListResponse) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{5}
}

func (x *GetReadingListResponse) GetEntries() []*ReadingListEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type DeleteReadingListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReadingListRequest) Reset() {
	*x = DeleteReadingListRequest{}
	mi := &file_readinglist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReadingListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReadingListRequest) ProtoMessage() {}

func (x *DeleteReadingListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReadingListRequest.ProtoReflect.Descriptor instead.
func (*DeleteReadingListRequest) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReadingListRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReadingListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedId     string                 `protobuf:"bytes,1,opt,name=deleted_id,json=deletedId,proto3" json:"deleted_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReadingListResponse) Reset() {
	*x = DeleteReadingListResponse{}
	mi := &file_readinglist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReadingListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReadingListResponse) ProtoMessage() {}

func (x *DeleteReadingListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_readinglist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReadingListResponse.ProtoReflect.Descriptor instead.
func (*DeleteReadingListResponse) Descriptor() ([]byte, []int) {
	return file_readinglist_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReadingListResponse) GetDeletedId() string {
	if x != nil {
		return x.DeletedId
	}
	return ""
}

func (x *DeleteReadingListResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteReadingListResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_readinglist_proto protoreflect.FileDescriptor

const file_readinglist_proto_rawDesc = "" +
	"\n" +
	"\x11readinglist.proto\x12\bgenproto\"\xaa\x02\n" +
	"\x10ReadingListEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x19\n" +
	"\bnovel_id\x18\x03 \x01(\tR\anovelId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x05 \x01(\x01R\x0ecurrentChapter\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\x12\x1f\n" +
	"\vis_favorite\x18\b \x01(\bR\n" +
	"isFavorite\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\fR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\fR\tupdatedAt\"\xe3\x01\n" +
	"\x17AddToReadingListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x19\n" +
	"\bnovel_id\x18\x02 \x01(\tR\anovelId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x04 \x01(\x01R\x0ecurrentChapter\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x14\n" +
	"\x05notes\x18\x06 \x01(\tR\x05notes\x12\x1f\n" +
	"\vis_favorite\x18\a \x01(\bR\n" +
	"isFavorite\"G\n" +
	"\x13ReadingListResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.genproto.ReadingListEntryR\x05entry\"\xba\x01\n" +
	"\x18UpdateReadingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fcurrent_chapter\x18\x03 \x01(\x01R\x0ecurrentChapter\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\x12\x1f\n" +
	"\vis_favorite\x18\x06 \x01(\bR\n" +
	"isFavorite\"v\n" +
	"\x15GetReadingListRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x04 \x01(\x04R\x04take\"N\n" +
	"\x16GetReadingListResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.genproto.ReadingListEntryR\aentries\"*\n" +
	"\x18DeleteReadingListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x19DeleteReadingListResponse\x12\x1d\n" +
	"\n" +
	"deleted_id\x18\x01 \x01(\tR\tdeletedId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xf9\x02\n" +
	"\x12ReadingListService\x12T\n" +
	"\x10AddToReadingList\x12!.genproto.AddToReadingListRequest\x1a\x1d.genproto.ReadingListResponse\x12V\n" +
	"\x11UpdateReadingList\x12\".genproto.UpdateReadingListRequest\x1a\x1d.genproto.ReadingListResponse\x12S\n" +
	"\x0eGetReadingList\x12\x1f.genproto.GetReadingListRequest\x1a .genproto.GetReadingListResponse\x12`\n" +
	"\x15RemoveFromReadingList\x12\".genproto.DeleteReadingListRequest\x1a#.genproto.DeleteReadingListResponseB/Z-github.com/wignn/micro-3/readinglist/genprotob\x06proto3"

var (
	file_readinglist_proto_rawDescOnce sync.Once
	file_readinglist_proto_rawDescData []byte
)

func file_readinglist_proto_rawDescGZIP() []byte {
	file_readinglist_proto_rawDescOnce.Do(func() {
		file_readinglist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_readinglist_proto_rawDesc), len(file_readinglist_proto_rawDesc)))
	})
	return file_readinglist_proto_rawDescData
}

var file_readinglist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_readinglist_proto_goTypes = []any{
	(*ReadingListEntry)(nil),          // 0: genproto.ReadingListEntry
	(*AddToReadingListRequest)(nil),   // 1: genproto.AddToReadingListRequest
	(*ReadingListResponse)(nil),       // 2: genproto.ReadingListResponse
	(*UpdateReadingListRequest)(nil),  // 3: genproto.UpdateReadingListRequest
	(*GetReadingListRequest)(nil),     // 4: genproto.GetReadingListRequest
	(*GetReadingListResponse)(nil),    // 5: genproto.GetReadingListResponse
	(*DeleteReadingListRequest)(nil),  // 6: genproto.DeleteReadingListRequest
	(*DeleteReadingListResponse)(nil), // 7: genproto.DeleteReadingListResponse
}
var file_readinglist_proto_depIdxs = []int32{
	0, // 0: genproto.ReadingListResponse.entry:type_name -> genproto.ReadingListEntry
	0, // 1: genproto.GetReadingListResponse.entries:type_name -> genproto.ReadingListEntry
	1, // 2: genproto.ReadingListService.AddToReadingList:input_type -> genproto.AddToReadingListRequest
	3, // 3: genproto.ReadingListService.UpdateReadingList:input_type -> genproto.UpdateReadingListRequest
	4, // 4: genproto.ReadingListService.GetReadingList:input_type -> genproto.GetReadingListRequest
	6, // 5: genproto.ReadingListService.RemoveFromReadingList:input_type -> genproto.DeleteReadingListRequest
	2, // 6: genproto.ReadingListService.AddToReadingList:output_type -> genproto.ReadingListResponse
	2, // 7: genproto.ReadingListService.UpdateReadingList:output_type -> genproto.ReadingListResponse
	5, // 8: genproto.ReadingListService.GetReadingList:output_type -> genproto.GetReadingListResponse
	7, // 9: genproto.ReadingListService.RemoveFromReadingList:output_type -> genproto.DeleteReadingListResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_readinglist_proto_init() }
func file_readinglist_proto_init() {
	if File_readinglist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_readinglist_proto_rawDesc), len(file_readinglist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_readinglist_proto_goTypes,
		DependencyIndexes: file_readinglist_proto_depIdxs,
		MessageInfos:      file_readinglist_proto_msgTypes,
	}.Build()
	File_readinglist_proto = out.File
	file_readinglist_proto_goTypes = nil
	file_readinglist_proto_depIdxs = nil
}
