// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: readinglist.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReadingListService_AddToReadingList_FullMethodName      = "/genproto.ReadingListService/AddToReadingList"
	ReadingListService_UpdateReadingList_FullMethodName     = "/genproto.ReadingListService/UpdateReadingList"
	ReadingListService_GetReadingList_FullMethodName        = "/genproto.ReadingListService/GetReadingList"
	ReadingListService_RemoveFromReadingList_FullMethodName = "/genproto.ReadingListService/RemoveFromReadingList"
)

// ReadingListServiceClient is the client API for ReadingListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadingListServiceClient interface {
	AddToReadingList(ctx context.Context, in *AddToReadingListRequest, opts ...grpc.CallOption) (*ReadingListResponse, error)
	UpdateReadingList(ctx context.Context, in *UpdateReadingListRequest, opts ...grpc.CallOption) (*ReadingListResponse, error)
	GetReadingList(ctx context.Context, in *GetReadingListRequest, opts ...grpc.CallOption) (*GetReadingListResponse, error)
	RemoveFromReadingList(ctx context.Context, in *DeleteReadingListRequest, opts ...grpc.CallOption) (*DeleteReadingListResponse, error)
}

type readingListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReadingListServiceClient(cc grpc.ClientConnInterface) ReadingListServiceClient {
	return &readingListServiceClient{cc}
}

func (c *readingListServiceClient) AddToReadingList(ctx context.Context, in *AddToReadingListRequest, opts ...grpc.CallOption) (*ReadingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadingListResponse)
	err := c.cc.Invoke(ctx, ReadingListService_AddToReadingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingListServiceClient) UpdateReadingList(ctx context.Context, in *UpdateReadingListRequest, opts ...grpc.CallOption) (*ReadingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadingListResponse)
	err := c.cc.Invoke(ctx, ReadingListService_UpdateReadingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingListServiceClient) GetReadingList(ctx context.Context, in *GetReadingListRequest, opts ...grpc.CallOption) (*GetReadingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReadingListResponse)
	err := c.cc.Invoke(ctx, ReadingListService_GetReadingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readingListServiceClient) RemoveFromReadingList(ctx context.Context, in *DeleteReadingListRequest, opts ...grpc.CallOption) (*DeleteReadingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteReadingListResponse)
	err := c.cc.Invoke(ctx, ReadingListService_RemoveFromReadingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadingListServiceServer is the server API for ReadingListService service.
// All implementations must embed UnimplementedReadingListServiceServer
// for forward compatibility.
type ReadingListServiceServer interface {
	AddToReadingList(context.Context, *AddToReadingListRequest) (*ReadingListResponse, error)
	UpdateReadingList(context.Context, *UpdateReadingListRequest) (*ReadingListResponse, error)
	GetReadingList(context.Context, *GetReadingListRequest) (*GetReadingListResponse, error)
	RemoveFromReadingList(context.Context, *DeleteReadingListRequest) (*DeleteReadingListResponse, error)
	mustEmbedUnimplementedReadingListServiceServer()
}

// UnimplementedReadingListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadingListServiceServer struct{}

func (UnimplementedReadingListServiceServer) AddToReadingList(context.Context, *AddToReadingListRequest) (*ReadingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToReadingList not implemented")
}
func (UnimplementedReadingListServiceServer) UpdateReadingList(context.Context, *UpdateReadingListRequest) (*ReadingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReadingList not implemented")
}
func (UnimplementedReadingListServiceServer) GetReadingList(context.Context, *GetReadingListRequest) (*GetReadingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReadingList not implemented")
}
func (UnimplementedReadingListServiceServer) RemoveFromReadingList(context.Context, *DeleteReadingListRequest) (*DeleteReadingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromReadingList not implemented")
}
func (UnimplementedReadingListServiceServer) mustEmbedUnimplementedReadingListServiceServer() {}
func (UnimplementedReadingListServiceServer) testEmbeddedByValue()                            {}

// UnsafeReadingListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadingListServiceServer will
// result in compilation errors.
type UnsafeReadingListServiceServer interface {
	mustEmbedUnimplementedReadingListServiceServer()
}

func RegisterReadingListServiceServer(s grpc.ServiceRegistrar, srv ReadingListServiceServer) {
	// If the following call panics, it indicates UnimplementedReadingListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReadingListService_ServiceDesc, srv)
}

func _ReadingListService_AddToReadingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToReadingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingListServiceServer).AddToReadingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingListService_AddToReadingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingListServiceServer).AddToReadingList(ctx, req.(*AddToReadingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingListService_UpdateReadingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReadingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingListServiceServer).UpdateReadingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingListService_UpdateReadingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingListServiceServer).UpdateReadingList(ctx, req.(*UpdateReadingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingListService_GetReadingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingListServiceServer).GetReadingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingListService_GetReadingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingListServiceServer).GetReadingList(ctx, req.(*GetReadingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadingListService_RemoveFromReadingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReadingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadingListServiceServer).RemoveFromReadingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadingListService_RemoveFromReadingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadingListServiceServer).RemoveFromReadingList(ctx, req.(*DeleteReadingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadingListService_ServiceDesc is the grpc.ServiceDesc for ReadingListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadingListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.ReadingListService",
	HandlerType: (*ReadingListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToReadingList",
			Handler:    _ReadingListService_AddToReadingList_Handler,
		},
		{
			MethodName: "UpdateReadingList",
			Handler:    _ReadingListService_UpdateReadingList_Handler,
		},
		{
			MethodName: "GetReadingList",
			Handler:    _ReadingListService_GetReadingList_Handler,
		},
		{
			MethodName: "RemoveFromReadingList",
			Handler:    _ReadingListService_RemoveFromReadingList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "readinglist.proto",
}
