// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AccountInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Author struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Bio       *string   `json:"bio,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type AuthorInput struct {
	Name string  `json:"name"`
	Bio  *string `json:"bio,omitempty"`
}

type Chapter struct {
	ID                string    `json:"id"`
	NovelID           string    `json:"novelId"`
	ChapterNumber     float64   `json:"chapterNumber"`
	Title             *string   `json:"title,omitempty"`
	TranslatorGroupID *string   `json:"translatorGroupId,omitempty"`
	SourceURL         *string   `json:"sourceUrl,omitempty"`
	CreatedAt         time.Time `json:"createdAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

type ChapterInput struct {
	NovelID           string  `json:"novelId"`
	ChapterNumber     float64 `json:"chapterNumber"`
	Title             *string `json:"title,omitempty"`
	TranslatorGroupID *string `json:"translatorGroupId,omitempty"`
	SourceURL         *string `json:"sourceUrl,omitempty"`
}

type DeleteResponse struct {
	DeletedID string `json:"deletedId"`
	Success   bool   `json:"success"`
	Message   string `json:"message"`
}

type EditAccountInput struct {
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	AvatarURL *string `json:"avatarUrl,omitempty"`
	Bio       *string `json:"bio,omitempty"`
}

type Genre struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Novel struct {
	ID               string    `json:"id"`
	Title            string    `json:"title"`
	AlternativeTitle *string   `json:"alternativeTitle,omitempty"`
	Description      *string   `json:"description,omitempty"`
	CoverImageURL    *string   `json:"coverImageUrl,omitempty"`
	Author           *Author   `json:"author,omitempty"`
	Status           string    `json:"status"`
	NovelType        string    `json:"novelType"`
	CountryOfOrigin  *string   `json:"countryOfOrigin,omitempty"`
	YearPublished    *int      `json:"yearPublished,omitempty"`
	TotalChapters    int       `json:"totalChapters"`
	RatingAvg        float64   `json:"ratingAvg"`
	RatingCount      int       `json:"ratingCount"`
	ViewCount        int       `json:"viewCount"`
	BookmarkCount    int       `json:"bookmarkCount"`
	Genres           []*Genre  `json:"genres"`
	Tags             []*Tag    `json:"tags"`
	CreatedAt        time.Time `json:"createdAt"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

type NovelFilterInput struct {
	Status          *string `json:"status,omitempty"`
	NovelType       *string `json:"novelType,omitempty"`
	CountryOfOrigin *string `json:"countryOfOrigin,omitempty"`
	GenreIds        []int   `json:"genreIds,omitempty"`
	TagIds          []int   `json:"tagIds,omitempty"`
	SortBy          *string `json:"sortBy,omitempty"`
	SortOrder       *string `json:"sortOrder,omitempty"`
}

type NovelInput struct {
	Title            string  `json:"title"`
	AlternativeTitle *string `json:"alternativeTitle,omitempty"`
	Description      *string `json:"description,omitempty"`
	CoverImageURL    *string `json:"coverImageUrl,omitempty"`
	AuthorID         *string `json:"authorId,omitempty"`
	Status           *string `json:"status,omitempty"`
	NovelType        *string `json:"novelType,omitempty"`
	CountryOfOrigin  *string `json:"countryOfOrigin,omitempty"`
	YearPublished    *int    `json:"yearPublished,omitempty"`
	GenreIds         []int   `json:"genreIds,omitempty"`
	TagIds           []int   `json:"tagIds,omitempty"`
}

type PaginationInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Query struct {
}

type RankedNovel struct {
	Rank   int     `json:"rank"`
	Novel  *Novel  `json:"novel"`
	Score  float64 `json:"score"`
	Change *int    `json:"change,omitempty"`
}

type ReadingListEntry struct {
	ID             string    `json:"id"`
	NovelID        string    `json:"novelId"`
	Status         string    `json:"status"`
	CurrentChapter float64   `json:"currentChapter"`
	Rating         *int      `json:"rating,omitempty"`
	Notes          *string   `json:"notes,omitempty"`
	IsFavorite     bool      `json:"isFavorite"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
}

type ReadingListInput struct {
	NovelID        string   `json:"novelId"`
	Status         string   `json:"status"`
	CurrentChapter *float64 `json:"currentChapter,omitempty"`
	Rating         *int     `json:"rating,omitempty"`
	Notes          *string  `json:"notes,omitempty"`
	IsFavorite     *bool    `json:"isFavorite,omitempty"`
}

type Review struct {
	ID        string    `json:"id"`
	NovelID   string    `json:"novelId"`
	AccountID string    `json:"accountId"`
	Rating    int       `json:"rating"`
	Title     *string   `json:"title,omitempty"`
	Content   *string   `json:"content,omitempty"`
	IsSpoiler bool      `json:"isSpoiler"`
	Upvotes   int       `json:"upvotes"`
	Downvotes int       `json:"downvotes"`
	CreatedAt time.Time `json:"createdAt"`
}

type ReviewInput struct {
	NovelID   string  `json:"novelId"`
	AccountID string  `json:"accountId"`
	Rating    int     `json:"rating"`
	Title     *string `json:"title,omitempty"`
	Content   *string `json:"content,omitempty"`
	IsSpoiler *bool   `json:"isSpoiler,omitempty"`
}

type Tag struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type TagInput struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

type Token struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int    `json:"expiresIn"`
}

type TranslationGroup struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	WebsiteURL  *string   `json:"websiteUrl,omitempty"`
	Description *string   `json:"description,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
}

type TranslationGroupInput struct {
	Name        string  `json:"name"`
	WebsiteURL  *string `json:"websiteUrl,omitempty"`
	Description *string `json:"description,omitempty"`
}

type AuthResponse struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	BackendToken *Token `json:"backendToken"`
}

type RankingPeriod string

const (
	RankingPeriodWeekly  RankingPeriod = "WEEKLY"
	RankingPeriodMonthly RankingPeriod = "MONTHLY"
	RankingPeriodAllTime RankingPeriod = "ALL_TIME"
)

var AllRankingPeriod = []RankingPeriod{
	RankingPeriodWeekly,
	RankingPeriodMonthly,
	RankingPeriodAllTime,
}

func (e RankingPeriod) IsValid() bool {
	switch e {
	case RankingPeriodWeekly, RankingPeriodMonthly, RankingPeriodAllTime:
		return true
	}
	return false
}

func (e RankingPeriod) String() string {
	return string(e)
}

func (e *RankingPeriod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RankingPeriod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RankingPeriod", str)
	}
	return nil
}

func (e RankingPeriod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RankingPeriod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RankingPeriod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RankingSortBy string

const (
	RankingSortByViews     RankingSortBy = "VIEWS"
	RankingSortByBookmarks RankingSortBy = "BOOKMARKS"
	RankingSortByRating    RankingSortBy = "RATING"
)

var AllRankingSortBy = []RankingSortBy{
	RankingSortByViews,
	RankingSortByBookmarks,
	RankingSortByRating,
}

func (e RankingSortBy) IsValid() bool {
	switch e {
	case RankingSortByViews, RankingSortByBookmarks, RankingSortByRating:
		return true
	}
	return false
}

func (e RankingSortBy) String() string {
	return string(e)
}

func (e *RankingSortBy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RankingSortBy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RankingSortBy", str)
	}
	return nil
}

func (e RankingSortBy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RankingSortBy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RankingSortBy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
