// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: review.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NovelId       string                 `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Rating        int32                  `protobuf:"varint,6,opt,name=rating,proto3" json:"rating,omitempty"`
	IsSpoiler     bool                   `protobuf:"varint,7,opt,name=is_spoiler,json=isSpoiler,proto3" json:"is_spoiler,omitempty"`
	Upvotes       int32                  `protobuf:"varint,8,opt,name=upvotes,proto3" json:"upvotes,omitempty"`
	Downvotes     int32                  `protobuf:"varint,9,opt,name=downvotes,proto3" json:"downvotes,omitempty"`
	CreatedAt     []byte                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *Review) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Review) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Review) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetIsSpoiler() bool {
	if x != nil {
		return x.IsSpoiler
	}
	return false
}

func (x *Review) GetUpvotes() int32 {
	if x != nil {
		return x.Upvotes
	}
	return 0
}

func (x *Review) GetDownvotes() int32 {
	if x != nil {
		return x.Downvotes
	}
	return 0
}

func (x *Review) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ReviewIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewIdRequest) Reset() {
	*x = ReviewIdRequest{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewIdRequest) ProtoMessage() {}

func (x *ReviewIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewIdRequest.ProtoReflect.Descriptor instead.
func (*ReviewIdRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NovelReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelId       string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Skip          uint64                 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NovelReviewsRequest) Reset() {
	*x = NovelReviewsRequest{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NovelReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NovelReviewsRequest) ProtoMessage() {}

func (x *NovelReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NovelReviewsRequest.ProtoReflect.Descriptor instead.
func (*NovelReviewsRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *NovelReviewsRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *NovelReviewsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *NovelReviewsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type PostReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelId       string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Rating        int32                  `protobuf:"varint,5,opt,name=rating,proto3" json:"rating,omitempty"`
	IsSpoiler     bool                   `protobuf:"varint,6,opt,name=is_spoiler,json=isSpoiler,proto3" json:"is_spoiler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostReviewRequest) Reset() {
	*x = PostReviewRequest{}
	mi := &file_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostReviewRequest) ProtoMessage() {}

func (x *PostReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostReviewRequest.ProtoReflect.Descriptor instead.
func (*PostReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{3}
}

func (x *PostReviewRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *PostReviewRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PostReviewRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *PostReviewRequest) GetIsSpoiler() bool {
	if x != nil {
		return x.IsSpoiler
	}
	return false
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type ReviewListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewListResponse) Reset() {
	*x = ReviewListResponse{}
	mi := &file_review_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewListResponse) ProtoMessage() {}

func (x *ReviewListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewListResponse.ProtoReflect.Descriptor instead.
func (*ReviewListResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewListResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type DeleteReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewRequest) Reset() {
	*x = DeleteReviewRequest{}
	mi := &file_review_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewRequest) ProtoMessage() {}

func (x *DeleteReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewRequest.ProtoReflect.Descriptor instead.
func (*DeleteReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReviewRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedId     string                 `protobuf:"bytes,1,opt,name=deleted_id,json=deletedId,proto3" json:"deleted_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReviewResponse) Reset() {
	*x = DeleteReviewResponse{}
	mi := &file_review_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReviewResponse) ProtoMessage() {}

func (x *DeleteReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReviewResponse.ProtoReflect.Descriptor instead.
func (*DeleteReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReviewResponse) GetDeletedId() string {
	if x != nil {
		return x.DeletedId
	}
	return ""
}

func (x *DeleteReviewResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteReviewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\x12\bgenproto\"\x90\x02\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnovel_id\x18\x02 \x01(\tR\anovelId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x05R\x06rating\x12\x1d\n" +
	"\n" +
	"is_spoiler\x18\a \x01(\bR\tisSpoiler\x12\x18\n" +
	"\aupvotes\x18\b \x01(\x05R\aupvotes\x12\x1c\n" +
	"\tdownvotes\x18\t \x01(\x05R\tdownvotes\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\fR\tcreatedAt\"!\n" +
	"\x0fReviewIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x13NovelReviewsRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x03 \x01(\x04R\x04take\"\xb4\x01\n" +
	"\x11PostReviewRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x05R\x06rating\x12\x1d\n" +
	"\n" +
	"is_spoiler\x18\x06 \x01(\bR\tisSpoiler\":\n" +
	"\x0eReviewResponse\x12(\n" +
	"\x06review\x18\x01 \x01(\v2\x10.genproto.ReviewR\x06review\"@\n" +
	"\x12ReviewListResponse\x12*\n" +
	"\areviews\x18\x01 \x03(\v2\x10.genproto.ReviewR\areviews\"%\n" +
	"\x13DeleteReviewRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x14DeleteReviewResponse\x12\x1d\n" +
	"\n" +
	"deleted_id\x18\x01 \x01(\tR\tdeletedId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess2\xaf\x02\n" +
	"\rReviewService\x12C\n" +
	"\n" +
	"PostReview\x12\x1b.genproto.PostReviewRequest\x1a\x18.genproto.ReviewResponse\x128\n" +
	"\tGetReview\x12\x19.genproto.ReviewIdRequest\x1a\x10.genproto.Review\x12P\n" +
	"\x11GetReviewsByNovel\x12\x1d.genproto.NovelReviewsRequest\x1a\x1c.genproto.ReviewListResponse\x12M\n" +
	"\fDeleteReview\x12\x1d.genproto.DeleteReviewRequest\x1a\x1e.genproto.DeleteReviewResponseB*Z(github.com/wignn/micro-3/review/genprotob\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_review_proto_goTypes = []any{
	(*Review)(nil),               // 0: genproto.Review
	(*ReviewIdRequest)(nil),      // 1: genproto.ReviewIdRequest
	(*NovelReviewsRequest)(nil),  // 2: genproto.NovelReviewsRequest
	(*PostReviewRequest)(nil),    // 3: genproto.PostReviewRequest
	(*ReviewResponse)(nil),       // 4: genproto.ReviewResponse
	(*ReviewListResponse)(nil),   // 5: genproto.ReviewListResponse
	(*DeleteReviewRequest)(nil),  // 6: genproto.DeleteReviewRequest
	(*DeleteReviewResponse)(nil), // 7: genproto.DeleteReviewResponse
}
var file_review_proto_depIdxs = []int32{
	0, // 0: genproto.ReviewResponse.review:type_name -> genproto.Review
	0, // 1: genproto.ReviewListResponse.reviews:type_name -> genproto.Review
	3, // 2: genproto.ReviewService.PostReview:input_type -> genproto.PostReviewRequest
	1, // 3: genproto.ReviewService.GetReview:input_type -> genproto.ReviewIdRequest
	2, // 4: genproto.ReviewService.GetReviewsByNovel:input_type -> genproto.NovelReviewsRequest
	6, // 5: genproto.ReviewService.DeleteReview:input_type -> genproto.DeleteReviewRequest
	4, // 6: genproto.ReviewService.PostReview:output_type -> genproto.ReviewResponse
	0, // 7: genproto.ReviewService.GetReview:output_type -> genproto.Review
	5, // 8: genproto.ReviewService.GetReviewsByNovel:output_type -> genproto.ReviewListResponse
	7, // 9: genproto.ReviewService.DeleteReview:output_type -> genproto.DeleteReviewResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
