// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: novel.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_novel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{0}
}

func (x *Genre) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Genre) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_novel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Author struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	CreatedAt     []byte                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Author) Reset() {
	*x = Author{}
	mi := &file_novel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Author) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Author) ProtoMessage() {}

func (x *Author) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Author.ProtoReflect.Descriptor instead.
func (*Author) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{2}
}

func (x *Author) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Author) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Author) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Author) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TranslationGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	WebsiteUrl    string                 `protobuf:"bytes,3,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     []byte                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationGroup) Reset() {
	*x = TranslationGroup{}
	mi := &file_novel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationGroup) ProtoMessage() {}

func (x *TranslationGroup) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationGroup.ProtoReflect.Descriptor instead.
func (*TranslationGroup) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{3}
}

func (x *TranslationGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TranslationGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TranslationGroup) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *TranslationGroup) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TranslationGroup) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Novel struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AlternativeTitle string                 `protobuf:"bytes,3,opt,name=alternative_title,json=alternativeTitle,proto3" json:"alternative_title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CoverImageUrl    string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	AuthorId         string                 `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	NovelType        string                 `protobuf:"bytes,8,opt,name=novel_type,json=novelType,proto3" json:"novel_type,omitempty"`
	CountryOfOrigin  string                 `protobuf:"bytes,9,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	YearPublished    int32                  `protobuf:"varint,10,opt,name=year_published,json=yearPublished,proto3" json:"year_published,omitempty"`
	TotalChapters    int32                  `protobuf:"varint,11,opt,name=total_chapters,json=totalChapters,proto3" json:"total_chapters,omitempty"`
	RatingAvg        float64                `protobuf:"fixed64,12,opt,name=rating_avg,json=ratingAvg,proto3" json:"rating_avg,omitempty"`
	RatingCount      int32                  `protobuf:"varint,13,opt,name=rating_count,json=ratingCount,proto3" json:"rating_count,omitempty"`
	ViewCount        int64                  `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	BookmarkCount    int32                  `protobuf:"varint,15,opt,name=bookmark_count,json=bookmarkCount,proto3" json:"bookmark_count,omitempty"`
	CreatedAt        []byte                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        []byte                 `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Genres           []*Genre               `protobuf:"bytes,18,rep,name=genres,proto3" json:"genres,omitempty"`
	Tags             []*Tag                 `protobuf:"bytes,19,rep,name=tags,proto3" json:"tags,omitempty"`
	Author           *Author                `protobuf:"bytes,20,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Novel) Reset() {
	*x = Novel{}
	mi := &file_novel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Novel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Novel) ProtoMessage() {}

func (x *Novel) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Novel.ProtoReflect.Descriptor instead.
func (*Novel) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{4}
}

func (x *Novel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Novel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Novel) GetAlternativeTitle() string {
	if x != nil {
		return x.AlternativeTitle
	}
	return ""
}

func (x *Novel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Novel) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *Novel) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Novel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Novel) GetNovelType() string {
	if x != nil {
		return x.NovelType
	}
	return ""
}

func (x *Novel) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *Novel) GetYearPublished() int32 {
	if x != nil {
		return x.YearPublished
	}
	return 0
}

func (x *Novel) GetTotalChapters() int32 {
	if x != nil {
		return x.TotalChapters
	}
	return 0
}

func (x *Novel) GetRatingAvg() float64 {
	if x != nil {
		return x.RatingAvg
	}
	return 0
}

func (x *Novel) GetRatingCount() int32 {
	if x != nil {
		return x.RatingCount
	}
	return 0
}

func (x *Novel) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Novel) GetBookmarkCount() int32 {
	if x != nil {
		return x.BookmarkCount
	}
	return 0
}

func (x *Novel) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Novel) GetUpdatedAt() []byte {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Novel) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Novel) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Novel) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type Chapter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NovelId           string                 `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	ChapterNumber     float64                `protobuf:"fixed64,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	TranslatorGroupId string                 `protobuf:"bytes,5,opt,name=translator_group_id,json=translatorGroupId,proto3" json:"translator_group_id,omitempty"`
	SourceUrl         string                 `protobuf:"bytes,6,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	CreatedAt         []byte                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         []byte                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	TranslatorGroup   *TranslationGroup      `protobuf:"bytes,9,opt,name=translator_group,json=translatorGroup,proto3" json:"translator_group,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_novel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{5}
}

func (x *Chapter) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chapter) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *Chapter) GetChapterNumber() float64 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *Chapter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chapter) GetTranslatorGroupId() string {
	if x != nil {
		return x.TranslatorGroupId
	}
	return ""
}

func (x *Chapter) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *Chapter) GetCreatedAt() []byte {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chapter) GetUpdatedAt() []byte {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Chapter) GetTranslatorGroup() *TranslationGroup {
	if x != nil {
		return x.TranslatorGroup
	}
	return nil
}

type RankedNovel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Novel         *Novel                 `protobuf:"bytes,2,opt,name=novel,proto3" json:"novel,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Change        int32                  `protobuf:"varint,4,opt,name=change,proto3" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankedNovel) Reset() {
	*x = RankedNovel{}
	mi := &file_novel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedNovel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedNovel) ProtoMessage() {}

func (x *RankedNovel) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedNovel.ProtoReflect.Descriptor instead.
func (*RankedNovel) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{6}
}

func (x *RankedNovel) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankedNovel) GetNovel() *Novel {
	if x != nil {
		return x.Novel
	}
	return nil
}

func (x *RankedNovel) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankedNovel) GetChange() int32 {
	if x != nil {
		return x.Change
	}
	return 0
}

type CreateNovelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	AlternativeTitle string                 `protobuf:"bytes,2,opt,name=alternative_title,json=alternativeTitle,proto3" json:"alternative_title,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CoverImageUrl    string                 `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	AuthorId         string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	NovelType        string                 `protobuf:"bytes,7,opt,name=novel_type,json=novelType,proto3" json:"novel_type,omitempty"`
	CountryOfOrigin  string                 `protobuf:"bytes,8,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	YearPublished    int32                  `protobuf:"varint,9,opt,name=year_published,json=yearPublished,proto3" json:"year_published,omitempty"`
	GenreIds         []int32                `protobuf:"varint,10,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	TagIds           []int32                `protobuf:"varint,11,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateNovelRequest) Reset() {
	*x = CreateNovelRequest{}
	mi := &file_novel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNovelRequest) ProtoMessage() {}

func (x *CreateNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNovelRequest.ProtoReflect.Descriptor instead.
func (*CreateNovelRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{7}
}

func (x *CreateNovelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateNovelRequest) GetAlternativeTitle() string {
	if x != nil {
		return x.AlternativeTitle
	}
	return ""
}

func (x *CreateNovelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateNovelRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateNovelRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateNovelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateNovelRequest) GetNovelType() string {
	if x != nil {
		return x.NovelType
	}
	return ""
}

func (x *CreateNovelRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *CreateNovelRequest) GetYearPublished() int32 {
	if x != nil {
		return x.YearPublished
	}
	return 0
}

func (x *CreateNovelRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *CreateNovelRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type NovelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Novel         *Novel                 `protobuf:"bytes,1,opt,name=novel,proto3" json:"novel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NovelResponse) Reset() {
	*x = NovelResponse{}
	mi := &file_novel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NovelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NovelResponse) ProtoMessage() {}

func (x *NovelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NovelResponse.ProtoReflect.Descriptor instead.
func (*NovelResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{8}
}

func (x *NovelResponse) GetNovel() *Novel {
	if x != nil {
		return x.Novel
	}
	return nil
}

type GetNovelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNovelRequest) Reset() {
	*x = GetNovelRequest{}
	mi := &file_novel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNovelRequest) ProtoMessage() {}

func (x *GetNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNovelRequest.ProtoReflect.Descriptor instead.
func (*GetNovelRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{9}
}

func (x *GetNovelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListNovelsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Skip            uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take            uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Query           string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	NovelType       string                 `protobuf:"bytes,5,opt,name=novel_type,json=novelType,proto3" json:"novel_type,omitempty"`
	CountryOfOrigin string                 `protobuf:"bytes,6,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	GenreIds        []int32                `protobuf:"varint,7,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	TagIds          []int32                `protobuf:"varint,8,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	SortBy          string                 `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder       string                 `protobuf:"bytes,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListNovelsRequest) Reset() {
	*x = ListNovelsRequest{}
	mi := &file_novel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNovelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelsRequest) ProtoMessage() {}

func (x *ListNovelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelsRequest.ProtoReflect.Descriptor instead.
func (*ListNovelsRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{10}
}

func (x *ListNovelsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListNovelsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *ListNovelsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListNovelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListNovelsRequest) GetNovelType() string {
	if x != nil {
		return x.NovelType
	}
	return ""
}

func (x *ListNovelsRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *ListNovelsRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *ListNovelsRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *ListNovelsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListNovelsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListNovelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Novels        []*Novel               `protobuf:"bytes,1,rep,name=novels,proto3" json:"novels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNovelsResponse) Reset() {
	*x = ListNovelsResponse{}
	mi := &file_novel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNovelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNovelsResponse) ProtoMessage() {}

func (x *ListNovelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNovelsResponse.ProtoReflect.Descriptor instead.
func (*ListNovelsResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{11}
}

func (x *ListNovelsResponse) GetNovels() []*Novel {
	if x != nil {
		return x.Novels
	}
	return nil
}

type UpdateNovelRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AlternativeTitle string                 `protobuf:"bytes,3,opt,name=alternative_title,json=alternativeTitle,proto3" json:"alternative_title,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CoverImageUrl    string                 `protobuf:"bytes,5,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	AuthorId         string                 `protobuf:"bytes,6,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Status           string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	NovelType        string                 `protobuf:"bytes,8,opt,name=novel_type,json=novelType,proto3" json:"novel_type,omitempty"`
	CountryOfOrigin  string                 `protobuf:"bytes,9,opt,name=country_of_origin,json=countryOfOrigin,proto3" json:"country_of_origin,omitempty"`
	YearPublished    int32                  `protobuf:"varint,10,opt,name=year_published,json=yearPublished,proto3" json:"year_published,omitempty"`
	GenreIds         []int32                `protobuf:"varint,11,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	TagIds           []int32                `protobuf:"varint,12,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateNovelRequest) Reset() {
	*x = UpdateNovelRequest{}
	mi := &file_novel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNovelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNovelRequest) ProtoMessage() {}

func (x *UpdateNovelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNovelRequest.ProtoReflect.Descriptor instead.
func (*UpdateNovelRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateNovelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateNovelRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateNovelRequest) GetAlternativeTitle() string {
	if x != nil {
		return x.AlternativeTitle
	}
	return ""
}

func (x *UpdateNovelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateNovelRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *UpdateNovelRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *UpdateNovelRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateNovelRequest) GetNovelType() string {
	if x != nil {
		return x.NovelType
	}
	return ""
}

func (x *UpdateNovelRequest) GetCountryOfOrigin() string {
	if x != nil {
		return x.CountryOfOrigin
	}
	return ""
}

func (x *UpdateNovelRequest) GetYearPublished() int32 {
	if x != nil {
		return x.YearPublished
	}
	return 0
}

func (x *UpdateNovelRequest) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *UpdateNovelRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_novel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedId     string                 `protobuf:"bytes,1,opt,name=deleted_id,json=deletedId,proto3" json:"deleted_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_novel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteResponse) GetDeletedId() string {
	if x != nil {
		return x.DeletedId
	}
	return ""
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateChapterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NovelId           string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	ChapterNumber     float64                `protobuf:"fixed64,2,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	TranslatorGroupId string                 `protobuf:"bytes,4,opt,name=translator_group_id,json=translatorGroupId,proto3" json:"translator_group_id,omitempty"`
	SourceUrl         string                 `protobuf:"bytes,5,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateChapterRequest) Reset() {
	*x = CreateChapterRequest{}
	mi := &file_novel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChapterRequest) ProtoMessage() {}

func (x *CreateChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChapterRequest.ProtoReflect.Descriptor instead.
func (*CreateChapterRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{15}
}

func (x *CreateChapterRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *CreateChapterRequest) GetChapterNumber() float64 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *CreateChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChapterRequest) GetTranslatorGroupId() string {
	if x != nil {
		return x.TranslatorGroupId
	}
	return ""
}

func (x *CreateChapterRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

type ChapterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapter       *Chapter               `protobuf:"bytes,1,opt,name=chapter,proto3" json:"chapter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterResponse) Reset() {
	*x = ChapterResponse{}
	mi := &file_novel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterResponse) ProtoMessage() {}

func (x *ChapterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterResponse.ProtoReflect.Descriptor instead.
func (*ChapterResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{16}
}

func (x *ChapterResponse) GetChapter() *Chapter {
	if x != nil {
		return x.Chapter
	}
	return nil
}

type GetChapterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChapterRequest) Reset() {
	*x = GetChapterRequest{}
	mi := &file_novel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChapterRequest) ProtoMessage() {}

func (x *GetChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChapterRequest.ProtoReflect.Descriptor instead.
func (*GetChapterRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{17}
}

func (x *GetChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListChaptersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelId       string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	Skip          uint64                 `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersRequest) Reset() {
	*x = ListChaptersRequest{}
	mi := &file_novel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersRequest) ProtoMessage() {}

func (x *ListChaptersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersRequest.ProtoReflect.Descriptor instead.
func (*ListChaptersRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{18}
}

func (x *ListChaptersRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *ListChaptersRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListChaptersRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListChaptersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chapters      []*Chapter             `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChaptersResponse) Reset() {
	*x = ListChaptersResponse{}
	mi := &file_novel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChaptersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChaptersResponse) ProtoMessage() {}

func (x *ListChaptersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChaptersResponse.ProtoReflect.Descriptor instead.
func (*ListChaptersResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{19}
}

func (x *ListChaptersResponse) GetChapters() []*Chapter {
	if x != nil {
		return x.Chapters
	}
	return nil
}

type UpdateChapterRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NovelId           string                 `protobuf:"bytes,2,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	ChapterNumber     float64                `protobuf:"fixed64,3,opt,name=chapter_number,json=chapterNumber,proto3" json:"chapter_number,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	TranslatorGroupId string                 `protobuf:"bytes,5,opt,name=translator_group_id,json=translatorGroupId,proto3" json:"translator_group_id,omitempty"`
	SourceUrl         string                 `protobuf:"bytes,6,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateChapterRequest) Reset() {
	*x = UpdateChapterRequest{}
	mi := &file_novel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChapterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChapterRequest) ProtoMessage() {}

func (x *UpdateChapterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChapterRequest.ProtoReflect.Descriptor instead.
func (*UpdateChapterRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateChapterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateChapterRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

func (x *UpdateChapterRequest) GetChapterNumber() float64 {
	if x != nil {
		return x.ChapterNumber
	}
	return 0
}

func (x *UpdateChapterRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateChapterRequest) GetTranslatorGroupId() string {
	if x != nil {
		return x.TranslatorGroupId
	}
	return ""
}

func (x *UpdateChapterRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

type CreateAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bio           string                 `protobuf:"bytes,2,opt,name=bio,proto3" json:"bio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthorRequest) Reset() {
	*x = CreateAuthorRequest{}
	mi := &file_novel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthorRequest) ProtoMessage() {}

func (x *CreateAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthorRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthorRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{21}
}

func (x *CreateAuthorRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAuthorRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type AuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        *Author                `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorResponse) Reset() {
	*x = AuthorResponse{}
	mi := &file_novel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorResponse) ProtoMessage() {}

func (x *AuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorResponse.ProtoReflect.Descriptor instead.
func (*AuthorResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{22}
}

func (x *AuthorResponse) GetAuthor() *Author {
	if x != nil {
		return x.Author
	}
	return nil
}

type ListAuthorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsRequest) Reset() {
	*x = ListAuthorsRequest{}
	mi := &file_novel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsRequest) ProtoMessage() {}

func (x *ListAuthorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsRequest.ProtoReflect.Descriptor instead.
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{23}
}

func (x *ListAuthorsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListAuthorsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *ListAuthorsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListAuthorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authors       []*Author              `protobuf:"bytes,1,rep,name=authors,proto3" json:"authors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuthorsResponse) Reset() {
	*x = ListAuthorsResponse{}
	mi := &file_novel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuthorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuthorsResponse) ProtoMessage() {}

func (x *ListAuthorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuthorsResponse.ProtoReflect.Descriptor instead.
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{24}
}

func (x *ListAuthorsResponse) GetAuthors() []*Author {
	if x != nil {
		return x.Authors
	}
	return nil
}

type CreateTranslationGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WebsiteUrl    string                 `protobuf:"bytes,2,opt,name=website_url,json=websiteUrl,proto3" json:"website_url,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTranslationGroupRequest) Reset() {
	*x = CreateTranslationGroupRequest{}
	mi := &file_novel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTranslationGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTranslationGroupRequest) ProtoMessage() {}

func (x *CreateTranslationGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTranslationGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateTranslationGroupRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{25}
}

func (x *CreateTranslationGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTranslationGroupRequest) GetWebsiteUrl() string {
	if x != nil {
		return x.WebsiteUrl
	}
	return ""
}

func (x *CreateTranslationGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TranslationGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *TranslationGroup      `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslationGroupResponse) Reset() {
	*x = TranslationGroupResponse{}
	mi := &file_novel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslationGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslationGroupResponse) ProtoMessage() {}

func (x *TranslationGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslationGroupResponse.ProtoReflect.Descriptor instead.
func (*TranslationGroupResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{26}
}

func (x *TranslationGroupResponse) GetGroup() *TranslationGroup {
	if x != nil {
		return x.Group
	}
	return nil
}

type ListTranslationGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skip          uint64                 `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationGroupsRequest) Reset() {
	*x = ListTranslationGroupsRequest{}
	mi := &file_novel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationGroupsRequest) ProtoMessage() {}

func (x *ListTranslationGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListTranslationGroupsRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{27}
}

func (x *ListTranslationGroupsRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListTranslationGroupsRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type ListTranslationGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*TranslationGroup    `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTranslationGroupsResponse) Reset() {
	*x = ListTranslationGroupsResponse{}
	mi := &file_novel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTranslationGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTranslationGroupsResponse) ProtoMessage() {}

func (x *ListTranslationGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTranslationGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListTranslationGroupsResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{28}
}

func (x *ListTranslationGroupsResponse) GetGroups() []*TranslationGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_novel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{29}
}

type GenreListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genres        []*Genre               `protobuf:"bytes,1,rep,name=genres,proto3" json:"genres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenreListResponse) Reset() {
	*x = GenreListResponse{}
	mi := &file_novel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenreListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenreListResponse) ProtoMessage() {}

func (x *GenreListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenreListResponse.ProtoReflect.Descriptor instead.
func (*GenreListResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{30}
}

func (x *GenreListResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_novel_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{31}
}

func (x *TagListResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_novel_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{32}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_novel_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{33}
}

func (x *TagResponse) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type RankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	SortBy        string                 `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	Skip          uint64                 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Take          uint64                 `protobuf:"varint,4,opt,name=take,proto3" json:"take,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingRequest) Reset() {
	*x = RankingRequest{}
	mi := &file_novel_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingRequest) ProtoMessage() {}

func (x *RankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingRequest.ProtoReflect.Descriptor instead.
func (*RankingRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{34}
}

func (x *RankingRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *RankingRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *RankingRequest) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *RankingRequest) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

type RankingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RankedNovels  []*RankedNovel         `protobuf:"bytes,1,rep,name=ranked_novels,json=rankedNovels,proto3" json:"ranked_novels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RankingResponse) Reset() {
	*x = RankingResponse{}
	mi := &file_novel_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankingResponse) ProtoMessage() {}

func (x *RankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankingResponse.ProtoReflect.Descriptor instead.
func (*RankingResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{35}
}

func (x *RankingResponse) GetRankedNovels() []*RankedNovel {
	if x != nil {
		return x.RankedNovels
	}
	return nil
}

type IncrementViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NovelId       string                 `protobuf:"bytes,1,opt,name=novel_id,json=novelId,proto3" json:"novel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementViewRequest) Reset() {
	*x = IncrementViewRequest{}
	mi := &file_novel_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewRequest) ProtoMessage() {}

func (x *IncrementViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewRequest.ProtoReflect.Descriptor instead.
func (*IncrementViewRequest) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{36}
}

func (x *IncrementViewRequest) GetNovelId() string {
	if x != nil {
		return x.NovelId
	}
	return ""
}

type IncrementViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewCount     int64                  `protobuf:"varint,1,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementViewResponse) Reset() {
	*x = IncrementViewResponse{}
	mi := &file_novel_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementViewResponse) ProtoMessage() {}

func (x *IncrementViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_novel_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementViewResponse.ProtoReflect.Descriptor instead.
func (*IncrementViewResponse) Descriptor() ([]byte, []int) {
	return file_novel_proto_rawDescGZIP(), []int{37}
}

func (x *IncrementViewResponse) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

var File_novel_proto protoreflect.FileDescriptor

const file_novel_proto_rawDesc = "" +
	"\n" +
	"\vnovel.proto\x12\bgenproto\"?\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"=\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"]\n" +
	"\x06Author\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x03 \x01(\tR\x03bio\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\fR\tcreatedAt\"\x98\x01\n" +
	"\x10TranslationGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vwebsite_url\x18\x03 \x01(\tR\n" +
	"websiteUrl\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\fR\tcreatedAt\"\xae\x05\n" +
	"\x05Novel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\x11alternative_title\x18\x03 \x01(\tR\x10alternativeTitle\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"novel_type\x18\b \x01(\tR\tnovelType\x12*\n" +
	"\x11country_of_origin\x18\t \x01(\tR\x0fcountryOfOrigin\x12%\n" +
	"\x0eyear_published\x18\n" +
	" \x01(\x05R\ryearPublished\x12%\n" +
	"\x0etotal_chapters\x18\v \x01(\x05R\rtotalChapters\x12\x1d\n" +
	"\n" +
	"rating_avg\x18\f \x01(\x01R\tratingAvg\x12!\n" +
	"\frating_count\x18\r \x01(\x05R\vratingCount\x12\x1d\n" +
	"\n" +
	"view_count\x18\x0e \x01(\x03R\tviewCount\x12%\n" +
	"\x0ebookmark_count\x18\x0f \x01(\x05R\rbookmarkCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\fR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\fR\tupdatedAt\x12'\n" +
	"\x06genres\x18\x12 \x03(\v2\x0f.genproto.GenreR\x06genres\x12!\n" +
	"\x04tags\x18\x13 \x03(\v2\r.genproto.TagR\x04tags\x12(\n" +
	"\x06author\x18\x14 \x01(\v2\x10.genproto.AuthorR\x06author\"\xc5\x02\n" +
	"\aChapter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnovel_id\x18\x02 \x01(\tR\anovelId\x12%\n" +
	"\x0echapter_number\x18\x03 \x01(\x01R\rchapterNumber\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12.\n" +
	"\x13translator_group_id\x18\x05 \x01(\tR\x11translatorGroupId\x12\x1d\n" +
	"\n" +
	"source_url\x18\x06 \x01(\tR\tsourceUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\fR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\fR\tupdatedAt\x12E\n" +
	"\x10translator_group\x18\t \x01(\v2\x1a.genproto.TranslationGroupR\x0ftranslatorGroup\"v\n" +
	"\vRankedNovel\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12%\n" +
	"\x05novel\x18\x02 \x01(\v2\x0f.genproto.NovelR\x05novel\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x16\n" +
	"\x06change\x18\x04 \x01(\x05R\x06change\"\xfe\x02\n" +
	"\x12CreateNovelRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12+\n" +
	"\x11alternative_title\x18\x02 \x01(\tR\x10alternativeTitle\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"novel_type\x18\a \x01(\tR\tnovelType\x12*\n" +
	"\x11country_of_origin\x18\b \x01(\tR\x0fcountryOfOrigin\x12%\n" +
	"\x0eyear_published\x18\t \x01(\x05R\ryearPublished\x12\x1b\n" +
	"\tgenre_ids\x18\n" +
	" \x03(\x05R\bgenreIds\x12\x17\n" +
	"\atag_ids\x18\v \x03(\x05R\x06tagIds\"6\n" +
	"\rNovelResponse\x12%\n" +
	"\x05novel\x18\x01 \x01(\v2\x0f.genproto.NovelR\x05novel\"!\n" +
	"\x0fGetNovelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x02\n" +
	"\x11ListNovelsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"novel_type\x18\x05 \x01(\tR\tnovelType\x12*\n" +
	"\x11country_of_origin\x18\x06 \x01(\tR\x0fcountryOfOrigin\x12\x1b\n" +
	"\tgenre_ids\x18\a \x03(\x05R\bgenreIds\x12\x17\n" +
	"\atag_ids\x18\b \x03(\x05R\x06tagIds\x12\x17\n" +
	"\asort_by\x18\t \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\tR\tsortOrder\"=\n" +
	"\x12ListNovelsResponse\x12'\n" +
	"\x06novels\x18\x01 \x03(\v2\x0f.genproto.NovelR\x06novels\"\x8e\x03\n" +
	"\x12UpdateNovelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12+\n" +
	"\x11alternative_title\x18\x03 \x01(\tR\x10alternativeTitle\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\x0fcover_image_url\x18\x05 \x01(\tR\rcoverImageUrl\x12\x1b\n" +
	"\tauthor_id\x18\x06 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"novel_type\x18\b \x01(\tR\tnovelType\x12*\n" +
	"\x11country_of_origin\x18\t \x01(\tR\x0fcountryOfOrigin\x12%\n" +
	"\x0eyear_published\x18\n" +
	" \x01(\x05R\ryearPublished\x12\x1b\n" +
	"\tgenre_ids\x18\v \x03(\x05R\bgenreIds\x12\x17\n" +
	"\atag_ids\x18\f \x03(\x05R\x06tagIds\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"c\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\n" +
	"deleted_id\x18\x01 \x01(\tR\tdeletedId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\xbd\x01\n" +
	"\x14CreateChapterRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12%\n" +
	"\x0echapter_number\x18\x02 \x01(\x01R\rchapterNumber\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12.\n" +
	"\x13translator_group_id\x18\x04 \x01(\tR\x11translatorGroupId\x12\x1d\n" +
	"\n" +
	"source_url\x18\x05 \x01(\tR\tsourceUrl\">\n" +
	"\x0fChapterResponse\x12+\n" +
	"\achapter\x18\x01 \x01(\v2\x11.genproto.ChapterR\achapter\"#\n" +
	"\x11GetChapterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"X\n" +
	"\x13ListChaptersRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x03 \x01(\x04R\x04take\"E\n" +
	"\x14ListChaptersResponse\x12-\n" +
	"\bchapters\x18\x01 \x03(\v2\x11.genproto.ChapterR\bchapters\"\xcd\x01\n" +
	"\x14UpdateChapterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bnovel_id\x18\x02 \x01(\tR\anovelId\x12%\n" +
	"\x0echapter_number\x18\x03 \x01(\x01R\rchapterNumber\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12.\n" +
	"\x13translator_group_id\x18\x05 \x01(\tR\x11translatorGroupId\x12\x1d\n" +
	"\n" +
	"source_url\x18\x06 \x01(\tR\tsourceUrl\";\n" +
	"\x13CreateAuthorRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03bio\x18\x02 \x01(\tR\x03bio\":\n" +
	"\x0eAuthorResponse\x12(\n" +
	"\x06author\x18\x01 \x01(\v2\x10.genproto.AuthorR\x06author\"L\n" +
	"\x12ListAuthorsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"A\n" +
	"\x13ListAuthorsResponse\x12*\n" +
	"\aauthors\x18\x01 \x03(\v2\x10.genproto.AuthorR\aauthors\"v\n" +
	"\x1dCreateTranslationGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vwebsite_url\x18\x02 \x01(\tR\n" +
	"websiteUrl\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"L\n" +
	"\x18TranslationGroupResponse\x120\n" +
	"\x05group\x18\x01 \x01(\v2\x1a.genproto.TranslationGroupR\x05group\"F\n" +
	"\x1cListTranslationGroupsRequest\x12\x12\n" +
	"\x04skip\x18\x01 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x02 \x01(\x04R\x04take\"S\n" +
	"\x1dListTranslationGroupsResponse\x122\n" +
	"\x06groups\x18\x01 \x03(\v2\x1a.genproto.TranslationGroupR\x06groups\"\x0e\n" +
	"\fEmptyRequest\"<\n" +
	"\x11GenreListResponse\x12'\n" +
	"\x06genres\x18\x01 \x03(\v2\x0f.genproto.GenreR\x06genres\"4\n" +
	"\x0fTagListResponse\x12!\n" +
	"\x04tags\x18\x01 \x03(\v2\r.genproto.TagR\x04tags\":\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\".\n" +
	"\vTagResponse\x12\x1f\n" +
	"\x03tag\x18\x01 \x01(\v2\r.genproto.TagR\x03tag\"i\n" +
	"\x0eRankingRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x17\n" +
	"\asort_by\x18\x02 \x01(\tR\x06sortBy\x12\x12\n" +
	"\x04skip\x18\x03 \x01(\x04R\x04skip\x12\x12\n" +
	"\x04take\x18\x04 \x01(\x04R\x04take\"M\n" +
	"\x0fRankingResponse\x12:\n" +
	"\rranked_novels\x18\x01 \x03(\v2\x15.genproto.RankedNovelR\frankedNovels\"1\n" +
	"\x14IncrementViewRequest\x12\x19\n" +
	"\bnovel_id\x18\x01 \x01(\tR\anovelId\"6\n" +
	"\x15IncrementViewResponse\x12\x1d\n" +
	"\n" +
	"view_count\x18\x01 \x01(\x03R\tviewCount2\x96\v\n" +
	"\fNovelService\x12D\n" +
	"\vCreateNovel\x12\x1c.genproto.CreateNovelRequest\x1a\x17.genproto.NovelResponse\x12>\n" +
	"\bGetNovel\x12\x19.genproto.GetNovelRequest\x1a\x17.genproto.NovelResponse\x12G\n" +
	"\n" +
	"ListNovels\x12\x1b.genproto.ListNovelsRequest\x1a\x1c.genproto.ListNovelsResponse\x12D\n" +
	"\vUpdateNovel\x12\x1c.genproto.UpdateNovelRequest\x1a\x17.genproto.NovelResponse\x12@\n" +
	"\vDeleteNovel\x12\x17.genproto.DeleteRequest\x1a\x18.genproto.DeleteResponse\x12J\n" +
	"\rCreateChapter\x12\x1e.genproto.CreateChapterRequest\x1a\x19.genproto.ChapterResponse\x12D\n" +
	"\n" +
	"GetChapter\x12\x1b.genproto.GetChapterRequest\x1a\x19.genproto.ChapterResponse\x12M\n" +
	"\fListChapters\x12\x1d.genproto.ListChaptersRequest\x1a\x1e.genproto.ListChaptersResponse\x12J\n" +
	"\rUpdateChapter\x12\x1e.genproto.UpdateChapterRequest\x1a\x19.genproto.ChapterResponse\x12B\n" +
	"\rDeleteChapter\x12\x17.genproto.DeleteRequest\x1a\x18.genproto.DeleteResponse\x12G\n" +
	"\fCreateAuthor\x12\x1d.genproto.CreateAuthorRequest\x1a\x18.genproto.AuthorResponse\x12J\n" +
	"\vListAuthors\x12\x1c.genproto.ListAuthorsRequest\x1a\x1d.genproto.ListAuthorsResponse\x12e\n" +
	"\x16CreateTranslationGroup\x12'.genproto.CreateTranslationGroupRequest\x1a\".genproto.TranslationGroupResponse\x12h\n" +
	"\x15ListTranslationGroups\x12&.genproto.ListTranslationGroupsRequest\x1a'.genproto.ListTranslationGroupsResponse\x12@\n" +
	"\tGetGenres\x12\x16.genproto.EmptyRequest\x1a\x1b.genproto.GenreListResponse\x12>\n" +
	"\tCreateTag\x12\x1a.genproto.CreateTagRequest\x1a\x15.genproto.TagResponse\x12<\n" +
	"\aGetTags\x12\x16.genproto.EmptyRequest\x1a\x19.genproto.TagListResponse\x12A\n" +
	"\n" +
	"GetRanking\x12\x18.genproto.RankingRequest\x1a\x19.genproto.RankingResponse\x12U\n" +
	"\x12IncrementViewCount\x12\x1e.genproto.IncrementViewRequest\x1a\x1f.genproto.IncrementViewResponseB)Z'github.com/wignn/micro-3/novel/genprotob\x06proto3"

var (
	file_novel_proto_rawDescOnce sync.Once
	file_novel_proto_rawDescData []byte
)

func file_novel_proto_rawDescGZIP() []byte {
	file_novel_proto_rawDescOnce.Do(func() {
		file_novel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_novel_proto_rawDesc), len(file_novel_proto_rawDesc)))
	})
	return file_novel_proto_rawDescData
}

var file_novel_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_novel_proto_goTypes = []any{
	(*Genre)(nil),                         // 0: genproto.Genre
	(*Tag)(nil),                           // 1: genproto.Tag
	(*Author)(nil),                        // 2: genproto.Author
	(*TranslationGroup)(nil),              // 3: genproto.TranslationGroup
	(*Novel)(nil),                         // 4: genproto.Novel
	(*Chapter)(nil),                       // 5: genproto.Chapter
	(*RankedNovel)(nil),                   // 6: genproto.RankedNovel
	(*CreateNovelRequest)(nil),            // 7: genproto.CreateNovelRequest
	(*NovelResponse)(nil),                 // 8: genproto.NovelResponse
	(*GetNovelRequest)(nil),               // 9: genproto.GetNovelRequest
	(*ListNovelsRequest)(nil),             // 10: genproto.ListNovelsRequest
	(*ListNovelsResponse)(nil),            // 11: genproto.ListNovelsResponse
	(*UpdateNovelRequest)(nil),            // 12: genproto.UpdateNovelRequest
	(*DeleteRequest)(nil),                 // 13: genproto.DeleteRequest
	(*DeleteResponse)(nil),                // 14: genproto.DeleteResponse
	(*CreateChapterRequest)(nil),          // 15: genproto.CreateChapterRequest
	(*ChapterResponse)(nil),               // 16: genproto.ChapterResponse
	(*GetChapterRequest)(nil),             // 17: genproto.GetChapterRequest
	(*ListChaptersRequest)(nil),           // 18: genproto.ListChaptersRequest
	(*ListChaptersResponse)(nil),          // 19: genproto.ListChaptersResponse
	(*UpdateChapterRequest)(nil),          // 20: genproto.UpdateChapterRequest
	(*CreateAuthorRequest)(nil),           // 21: genproto.CreateAuthorRequest
	(*AuthorResponse)(nil),                // 22: genproto.AuthorResponse
	(*ListAuthorsRequest)(nil),            // 23: genproto.ListAuthorsRequest
	(*ListAuthorsResponse)(nil),           // 24: genproto.ListAuthorsResponse
	(*CreateTranslationGroupRequest)(nil), // 25: genproto.CreateTranslationGroupRequest
	(*TranslationGroupResponse)(nil),      // 26: genproto.TranslationGroupResponse
	(*ListTranslationGroupsRequest)(nil),  // 27: genproto.ListTranslationGroupsRequest
	(*ListTranslationGroupsResponse)(nil), // 28: genproto.ListTranslationGroupsResponse
	(*EmptyRequest)(nil),                  // 29: genproto.EmptyRequest
	(*GenreListResponse)(nil),             // 30: genproto.GenreListResponse
	(*TagListResponse)(nil),               // 31: genproto.TagListResponse
	(*CreateTagRequest)(nil),              // 32: genproto.CreateTagRequest
	(*TagResponse)(nil),                   // 33: genproto.TagResponse
	(*RankingRequest)(nil),                // 34: genproto.RankingRequest
	(*RankingResponse)(nil),               // 35: genproto.RankingResponse
	(*IncrementViewRequest)(nil),          // 36: genproto.IncrementViewRequest
	(*IncrementViewResponse)(nil),         // 37: genproto.IncrementViewResponse
}
var file_novel_proto_depIdxs = []int32{
	0,  // 0: genproto.Novel.genres:type_name -> genproto.Genre
	1,  // 1: genproto.Novel.tags:type_name -> genproto.Tag
	2,  // 2: genproto.Novel.author:type_name -> genproto.Author
	3,  // 3: genproto.Chapter.translator_group:type_name -> genproto.TranslationGroup
	4,  // 4: genproto.RankedNovel.novel:type_name -> genproto.Novel
	4,  // 5: genproto.NovelResponse.novel:type_name -> genproto.Novel
	4,  // 6: genproto.ListNovelsResponse.novels:type_name -> genproto.Novel
	5,  // 7: genproto.ChapterResponse.chapter:type_name -> genproto.Chapter
	5,  // 8: genproto.ListChaptersResponse.chapters:type_name -> genproto.Chapter
	2,  // 9: genproto.AuthorResponse.author:type_name -> genproto.Author
	2,  // 10: genproto.ListAuthorsResponse.authors:type_name -> genproto.Author
	3,  // 11: genproto.TranslationGroupResponse.group:type_name -> genproto.TranslationGroup
	3,  // 12: genproto.ListTranslationGroupsResponse.groups:type_name -> genproto.TranslationGroup
	0,  // 13: genproto.GenreListResponse.genres:type_name -> genproto.Genre
	1,  // 14: genproto.TagListResponse.tags:type_name -> genproto.Tag
	1,  // 15: genproto.TagResponse.tag:type_name -> genproto.Tag
	6,  // 16: genproto.RankingResponse.ranked_novels:type_name -> genproto.RankedNovel
	7,  // 17: genproto.NovelService.CreateNovel:input_type -> genproto.CreateNovelRequest
	9,  // 18: genproto.NovelService.GetNovel:input_type -> genproto.GetNovelRequest
	10, // 19: genproto.NovelService.ListNovels:input_type -> genproto.ListNovelsRequest
	12, // 20: genproto.NovelService.UpdateNovel:input_type -> genproto.UpdateNovelRequest
	13, // 21: genproto.NovelService.DeleteNovel:input_type -> genproto.DeleteRequest
	15, // 22: genproto.NovelService.CreateChapter:input_type -> genproto.CreateChapterRequest
	17, // 23: genproto.NovelService.GetChapter:input_type -> genproto.GetChapterRequest
	18, // 24: genproto.NovelService.ListChapters:input_type -> genproto.ListChaptersRequest
	20, // 25: genproto.NovelService.UpdateChapter:input_type -> genproto.UpdateChapterRequest
	13, // 26: genproto.NovelService.DeleteChapter:input_type -> genproto.DeleteRequest
	21, // 27: genproto.NovelService.CreateAuthor:input_type -> genproto.CreateAuthorRequest
	23, // 28: genproto.NovelService.ListAuthors:input_type -> genproto.ListAuthorsRequest
	25, // 29: genproto.NovelService.CreateTranslationGroup:input_type -> genproto.CreateTranslationGroupRequest
	27, // 30: genproto.NovelService.ListTranslationGroups:input_type -> genproto.ListTranslationGroupsRequest
	29, // 31: genproto.NovelService.GetGenres:input_type -> genproto.EmptyRequest
	32, // 32: genproto.NovelService.CreateTag:input_type -> genproto.CreateTagRequest
	29, // 33: genproto.NovelService.GetTags:input_type -> genproto.EmptyRequest
	34, // 34: genproto.NovelService.GetRanking:input_type -> genproto.RankingRequest
	36, // 35: genproto.NovelService.IncrementViewCount:input_type -> genproto.IncrementViewRequest
	8,  // 36: genproto.NovelService.CreateNovel:output_type -> genproto.NovelResponse
	8,  // 37: genproto.NovelService.GetNovel:output_type -> genproto.NovelResponse
	11, // 38: genproto.NovelService.ListNovels:output_type -> genproto.ListNovelsResponse
	8,  // 39: genproto.NovelService.UpdateNovel:output_type -> genproto.NovelResponse
	14, // 40: genproto.NovelService.DeleteNovel:output_type -> genproto.DeleteResponse
	16, // 41: genproto.NovelService.CreateChapter:output_type -> genproto.ChapterResponse
	16, // 42: genproto.NovelService.GetChapter:output_type -> genproto.ChapterResponse
	19, // 43: genproto.NovelService.ListChapters:output_type -> genproto.ListChaptersResponse
	16, // 44: genproto.NovelService.UpdateChapter:output_type -> genproto.ChapterResponse
	14, // 45: genproto.NovelService.DeleteChapter:output_type -> genproto.DeleteResponse
	22, // 46: genproto.NovelService.CreateAuthor:output_type -> genproto.AuthorResponse
	24, // 47: genproto.NovelService.ListAuthors:output_type -> genproto.ListAuthorsResponse
	26, // 48: genproto.NovelService.CreateTranslationGroup:output_type -> genproto.TranslationGroupResponse
	28, // 49: genproto.NovelService.ListTranslationGroups:output_type -> genproto.ListTranslationGroupsResponse
	30, // 50: genproto.NovelService.GetGenres:output_type -> genproto.GenreListResponse
	33, // 51: genproto.NovelService.CreateTag:output_type -> genproto.TagResponse
	31, // 52: genproto.NovelService.GetTags:output_type -> genproto.TagListResponse
	35, // 53: genproto.NovelService.GetRanking:output_type -> genproto.RankingResponse
	37, // 54: genproto.NovelService.IncrementViewCount:output_type -> genproto.IncrementViewResponse
	36, // [36:55] is the sub-list for method output_type
	17, // [17:36] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_novel_proto_init() }
func file_novel_proto_init() {
	if File_novel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_novel_proto_rawDesc), len(file_novel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_novel_proto_goTypes,
		DependencyIndexes: file_novel_proto_depIdxs,
		MessageInfos:      file_novel_proto_msgTypes,
	}.Build()
	File_novel_proto = out.File
	file_novel_proto_goTypes = nil
	file_novel_proto_depIdxs = nil
}
