// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.9
// source: novel.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NovelService_CreateNovel_FullMethodName            = "/genproto.NovelService/CreateNovel"
	NovelService_GetNovel_FullMethodName               = "/genproto.NovelService/GetNovel"
	NovelService_ListNovels_FullMethodName             = "/genproto.NovelService/ListNovels"
	NovelService_UpdateNovel_FullMethodName            = "/genproto.NovelService/UpdateNovel"
	NovelService_DeleteNovel_FullMethodName            = "/genproto.NovelService/DeleteNovel"
	NovelService_CreateChapter_FullMethodName          = "/genproto.NovelService/CreateChapter"
	NovelService_GetChapter_FullMethodName             = "/genproto.NovelService/GetChapter"
	NovelService_ListChapters_FullMethodName           = "/genproto.NovelService/ListChapters"
	NovelService_UpdateChapter_FullMethodName          = "/genproto.NovelService/UpdateChapter"
	NovelService_DeleteChapter_FullMethodName          = "/genproto.NovelService/DeleteChapter"
	NovelService_CreateAuthor_FullMethodName           = "/genproto.NovelService/CreateAuthor"
	NovelService_ListAuthors_FullMethodName            = "/genproto.NovelService/ListAuthors"
	NovelService_CreateTranslationGroup_FullMethodName = "/genproto.NovelService/CreateTranslationGroup"
	NovelService_ListTranslationGroups_FullMethodName  = "/genproto.NovelService/ListTranslationGroups"
	NovelService_GetGenres_FullMethodName              = "/genproto.NovelService/GetGenres"
	NovelService_GetTags_FullMethodName                = "/genproto.NovelService/GetTags"
	NovelService_GetRanking_FullMethodName             = "/genproto.NovelService/GetRanking"
	NovelService_IncrementViewCount_FullMethodName     = "/genproto.NovelService/IncrementViewCount"
)

// NovelServiceClient is the client API for NovelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NovelServiceClient interface {
	// Novel CRUD
	CreateNovel(ctx context.Context, in *CreateNovelRequest, opts ...grpc.CallOption) (*NovelResponse, error)
	GetNovel(ctx context.Context, in *GetNovelRequest, opts ...grpc.CallOption) (*NovelResponse, error)
	ListNovels(ctx context.Context, in *ListNovelsRequest, opts ...grpc.CallOption) (*ListNovelsResponse, error)
	UpdateNovel(ctx context.Context, in *UpdateNovelRequest, opts ...grpc.CallOption) (*NovelResponse, error)
	DeleteNovel(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Chapter CRUD
	CreateChapter(ctx context.Context, in *CreateChapterRequest, opts ...grpc.CallOption) (*ChapterResponse, error)
	GetChapter(ctx context.Context, in *GetChapterRequest, opts ...grpc.CallOption) (*ChapterResponse, error)
	ListChapters(ctx context.Context, in *ListChaptersRequest, opts ...grpc.CallOption) (*ListChaptersResponse, error)
	UpdateChapter(ctx context.Context, in *UpdateChapterRequest, opts ...grpc.CallOption) (*ChapterResponse, error)
	DeleteChapter(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Author
	CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*AuthorResponse, error)
	ListAuthors(ctx context.Context, in *ListAuthorsRequest, opts ...grpc.CallOption) (*ListAuthorsResponse, error)
	// Translation Group
	CreateTranslationGroup(ctx context.Context, in *CreateTranslationGroupRequest, opts ...grpc.CallOption) (*TranslationGroupResponse, error)
	ListTranslationGroups(ctx context.Context, in *ListTranslationGroupsRequest, opts ...grpc.CallOption) (*ListTranslationGroupsResponse, error)
	// Genre & Tag
	GetGenres(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GenreListResponse, error)
	GetTags(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*TagListResponse, error)
	// Ranking
	GetRanking(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*RankingResponse, error)
	// View count
	IncrementViewCount(ctx context.Context, in *IncrementViewRequest, opts ...grpc.CallOption) (*IncrementViewResponse, error)
}

type novelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNovelServiceClient(cc grpc.ClientConnInterface) NovelServiceClient {
	return &novelServiceClient{cc}
}

func (c *novelServiceClient) CreateNovel(ctx context.Context, in *CreateNovelRequest, opts ...grpc.CallOption) (*NovelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NovelResponse)
	err := c.cc.Invoke(ctx, NovelService_CreateNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) GetNovel(ctx context.Context, in *GetNovelRequest, opts ...grpc.CallOption) (*NovelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NovelResponse)
	err := c.cc.Invoke(ctx, NovelService_GetNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListNovels(ctx context.Context, in *ListNovelsRequest, opts ...grpc.CallOption) (*ListNovelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNovelsResponse)
	err := c.cc.Invoke(ctx, NovelService_ListNovels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) UpdateNovel(ctx context.Context, in *UpdateNovelRequest, opts ...grpc.CallOption) (*NovelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NovelResponse)
	err := c.cc.Invoke(ctx, NovelService_UpdateNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) DeleteNovel(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NovelService_DeleteNovel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) CreateChapter(ctx context.Context, in *CreateChapterRequest, opts ...grpc.CallOption) (*ChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChapterResponse)
	err := c.cc.Invoke(ctx, NovelService_CreateChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) GetChapter(ctx context.Context, in *GetChapterRequest, opts ...grpc.CallOption) (*ChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChapterResponse)
	err := c.cc.Invoke(ctx, NovelService_GetChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListChapters(ctx context.Context, in *ListChaptersRequest, opts ...grpc.CallOption) (*ListChaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChaptersResponse)
	err := c.cc.Invoke(ctx, NovelService_ListChapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) UpdateChapter(ctx context.Context, in *UpdateChapterRequest, opts ...grpc.CallOption) (*ChapterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChapterResponse)
	err := c.cc.Invoke(ctx, NovelService_UpdateChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) DeleteChapter(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, NovelService_DeleteChapter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) CreateAuthor(ctx context.Context, in *CreateAuthorRequest, opts ...grpc.CallOption) (*AuthorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorResponse)
	err := c.cc.Invoke(ctx, NovelService_CreateAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListAuthors(ctx context.Context, in *ListAuthorsRequest, opts ...grpc.CallOption) (*ListAuthorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuthorsResponse)
	err := c.cc.Invoke(ctx, NovelService_ListAuthors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) CreateTranslationGroup(ctx context.Context, in *CreateTranslationGroupRequest, opts ...grpc.CallOption) (*TranslationGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranslationGroupResponse)
	err := c.cc.Invoke(ctx, NovelService_CreateTranslationGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) ListTranslationGroups(ctx context.Context, in *ListTranslationGroupsRequest, opts ...grpc.CallOption) (*ListTranslationGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTranslationGroupsResponse)
	err := c.cc.Invoke(ctx, NovelService_ListTranslationGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) GetGenres(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*GenreListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenreListResponse)
	err := c.cc.Invoke(ctx, NovelService_GetGenres_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) GetTags(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*TagListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagListResponse)
	err := c.cc.Invoke(ctx, NovelService_GetTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) GetRanking(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*RankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RankingResponse)
	err := c.cc.Invoke(ctx, NovelService_GetRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novelServiceClient) IncrementViewCount(ctx context.Context, in *IncrementViewRequest, opts ...grpc.CallOption) (*IncrementViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementViewResponse)
	err := c.cc.Invoke(ctx, NovelService_IncrementViewCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NovelServiceServer is the server API for NovelService service.
// All implementations must embed UnimplementedNovelServiceServer
// for forward compatibility.
type NovelServiceServer interface {
	// Novel CRUD
	CreateNovel(context.Context, *CreateNovelRequest) (*NovelResponse, error)
	GetNovel(context.Context, *GetNovelRequest) (*NovelResponse, error)
	ListNovels(context.Context, *ListNovelsRequest) (*ListNovelsResponse, error)
	UpdateNovel(context.Context, *UpdateNovelRequest) (*NovelResponse, error)
	DeleteNovel(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Chapter CRUD
	CreateChapter(context.Context, *CreateChapterRequest) (*ChapterResponse, error)
	GetChapter(context.Context, *GetChapterRequest) (*ChapterResponse, error)
	ListChapters(context.Context, *ListChaptersRequest) (*ListChaptersResponse, error)
	UpdateChapter(context.Context, *UpdateChapterRequest) (*ChapterResponse, error)
	DeleteChapter(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Author
	CreateAuthor(context.Context, *CreateAuthorRequest) (*AuthorResponse, error)
	ListAuthors(context.Context, *ListAuthorsRequest) (*ListAuthorsResponse, error)
	// Translation Group
	CreateTranslationGroup(context.Context, *CreateTranslationGroupRequest) (*TranslationGroupResponse, error)
	ListTranslationGroups(context.Context, *ListTranslationGroupsRequest) (*ListTranslationGroupsResponse, error)
	// Genre & Tag
	GetGenres(context.Context, *EmptyRequest) (*GenreListResponse, error)
	GetTags(context.Context, *EmptyRequest) (*TagListResponse, error)
	// Ranking
	GetRanking(context.Context, *RankingRequest) (*RankingResponse, error)
	// View count
	IncrementViewCount(context.Context, *IncrementViewRequest) (*IncrementViewResponse, error)
	mustEmbedUnimplementedNovelServiceServer()
}

// UnimplementedNovelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNovelServiceServer struct{}

func (UnimplementedNovelServiceServer) CreateNovel(context.Context, *CreateNovelRequest) (*NovelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNovel not implemented")
}
func (UnimplementedNovelServiceServer) GetNovel(context.Context, *GetNovelRequest) (*NovelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNovel not implemented")
}
func (UnimplementedNovelServiceServer) ListNovels(context.Context, *ListNovelsRequest) (*ListNovelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNovels not implemented")
}
func (UnimplementedNovelServiceServer) UpdateNovel(context.Context, *UpdateNovelRequest) (*NovelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNovel not implemented")
}
func (UnimplementedNovelServiceServer) DeleteNovel(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNovel not implemented")
}
func (UnimplementedNovelServiceServer) CreateChapter(context.Context, *CreateChapterRequest) (*ChapterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChapter not implemented")
}
func (UnimplementedNovelServiceServer) GetChapter(context.Context, *GetChapterRequest) (*ChapterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChapter not implemented")
}
func (UnimplementedNovelServiceServer) ListChapters(context.Context, *ListChaptersRequest) (*ListChaptersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListChapters not implemented")
}
func (UnimplementedNovelServiceServer) UpdateChapter(context.Context, *UpdateChapterRequest) (*ChapterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChapter not implemented")
}
func (UnimplementedNovelServiceServer) DeleteChapter(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChapter not implemented")
}
func (UnimplementedNovelServiceServer) CreateAuthor(context.Context, *CreateAuthorRequest) (*AuthorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthor not implemented")
}
func (UnimplementedNovelServiceServer) ListAuthors(context.Context, *ListAuthorsRequest) (*ListAuthorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuthors not implemented")
}
func (UnimplementedNovelServiceServer) CreateTranslationGroup(context.Context, *CreateTranslationGroupRequest) (*TranslationGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTranslationGroup not implemented")
}
func (UnimplementedNovelServiceServer) ListTranslationGroups(context.Context, *ListTranslationGroupsRequest) (*ListTranslationGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTranslationGroups not implemented")
}
func (UnimplementedNovelServiceServer) GetGenres(context.Context, *EmptyRequest) (*GenreListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGenres not implemented")
}
func (UnimplementedNovelServiceServer) GetTags(context.Context, *EmptyRequest) (*TagListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTags not implemented")
}
func (UnimplementedNovelServiceServer) GetRanking(context.Context, *RankingRequest) (*RankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRanking not implemented")
}
func (UnimplementedNovelServiceServer) IncrementViewCount(context.Context, *IncrementViewRequest) (*IncrementViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IncrementViewCount not implemented")
}
func (UnimplementedNovelServiceServer) mustEmbedUnimplementedNovelServiceServer() {}
func (UnimplementedNovelServiceServer) testEmbeddedByValue()                      {}

// UnsafeNovelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NovelServiceServer will
// result in compilation errors.
type UnsafeNovelServiceServer interface {
	mustEmbedUnimplementedNovelServiceServer()
}

func RegisterNovelServiceServer(s grpc.ServiceRegistrar, srv NovelServiceServer) {
	// If the following call panics, it indicates UnimplementedNovelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NovelService_ServiceDesc, srv)
}

func _NovelService_CreateNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateNovel(ctx, req.(*CreateNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_GetNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetNovel(ctx, req.(*GetNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListNovels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNovelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListNovels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListNovels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListNovels(ctx, req.(*ListNovelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_UpdateNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNovelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).UpdateNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_UpdateNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).UpdateNovel(ctx, req.(*UpdateNovelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_DeleteNovel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).DeleteNovel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_DeleteNovel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).DeleteNovel(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_CreateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateChapter(ctx, req.(*CreateChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_GetChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetChapter(ctx, req.(*GetChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListChapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListChapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListChapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListChapters(ctx, req.(*ListChaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_UpdateChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).UpdateChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_UpdateChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).UpdateChapter(ctx, req.(*UpdateChapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_DeleteChapter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).DeleteChapter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_DeleteChapter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).DeleteChapter(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_CreateAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateAuthor(ctx, req.(*CreateAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListAuthors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuthorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListAuthors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListAuthors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListAuthors(ctx, req.(*ListAuthorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_CreateTranslationGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTranslationGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).CreateTranslationGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_CreateTranslationGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).CreateTranslationGroup(ctx, req.(*CreateTranslationGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_ListTranslationGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTranslationGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).ListTranslationGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_ListTranslationGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).ListTranslationGroups(ctx, req.(*ListTranslationGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_GetGenres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetGenres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetGenres_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetGenres(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetTags(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_GetRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).GetRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_GetRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).GetRanking(ctx, req.(*RankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovelService_IncrementViewCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovelServiceServer).IncrementViewCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovelService_IncrementViewCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovelServiceServer).IncrementViewCount(ctx, req.(*IncrementViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NovelService_ServiceDesc is the grpc.ServiceDesc for NovelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NovelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.NovelService",
	HandlerType: (*NovelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNovel",
			Handler:    _NovelService_CreateNovel_Handler,
		},
		{
			MethodName: "GetNovel",
			Handler:    _NovelService_GetNovel_Handler,
		},
		{
			MethodName: "ListNovels",
			Handler:    _NovelService_ListNovels_Handler,
		},
		{
			MethodName: "UpdateNovel",
			Handler:    _NovelService_UpdateNovel_Handler,
		},
		{
			MethodName: "DeleteNovel",
			Handler:    _NovelService_DeleteNovel_Handler,
		},
		{
			MethodName: "CreateChapter",
			Handler:    _NovelService_CreateChapter_Handler,
		},
		{
			MethodName: "GetChapter",
			Handler:    _NovelService_GetChapter_Handler,
		},
		{
			MethodName: "ListChapters",
			Handler:    _NovelService_ListChapters_Handler,
		},
		{
			MethodName: "UpdateChapter",
			Handler:    _NovelService_UpdateChapter_Handler,
		},
		{
			MethodName: "DeleteChapter",
			Handler:    _NovelService_DeleteChapter_Handler,
		},
		{
			MethodName: "CreateAuthor",
			Handler:    _NovelService_CreateAuthor_Handler,
		},
		{
			MethodName: "ListAuthors",
			Handler:    _NovelService_ListAuthors_Handler,
		},
		{
			MethodName: "CreateTranslationGroup",
			Handler:    _NovelService_CreateTranslationGroup_Handler,
		},
		{
			MethodName: "ListTranslationGroups",
			Handler:    _NovelService_ListTranslationGroups_Handler,
		},
		{
			MethodName: "GetGenres",
			Handler:    _NovelService_GetGenres_Handler,
		},
		{
			MethodName: "GetTags",
			Handler:    _NovelService_GetTags_Handler,
		},
		{
			MethodName: "GetRanking",
			Handler:    _NovelService_GetRanking_Handler,
		},
		{
			MethodName: "IncrementViewCount",
			Handler:    _NovelService_IncrementViewCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "novel.proto",
}
